DROP DATABASE IF EXISTS universite;

CREATE DATABASE universite
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'fr_FR.UTF-8'
    LC_CTYPE = 'fr_FR.UTF-8'
    CONNECTION LIMIT = -1;

CREATE TABLE etudiants (
    id_etudiants INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    age INTEGER CHECK (age >= 16 AND age <= 100),
    email VARCHAR(100) UNIQUE NOT NULL,
    date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actif BOOLEAN DEFAULT TRUE,

    CONSTRAINT check_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

INSERT INTO etudiants (nom, prenom, age, email) VALUES
('Dupont', 'Jean', 20, 'jean.dupont@email.com'),
('Martin', 'Marie', 22, 'marie.martin@email.com');

SELECT
    id_etudiants as "ID Étudiant",
    UPPER(nom) as "Nom",
    INITCAP(prenom) as "Prénom",
    age as "Âge",
    email as "Adresse Email",
    TO_CHAR(date_inscription, 'DD/MM/YYYY') as "Date d'inscription"
FROM etudiants;

SELECT
    nom,
    prenom,
    age,
    email
FROM etudiants
WHERE age >= 18
ORDER BY nom, prenom;

SELECT *
FROM etudiants
WHERE nom LIKE 'D%'
ORDER BY prenom;

SELECT
    COUNT(*) as "Nombre total d'étudiants",
    AVG(age) as "Âge moyen",
    MIN(age) as "Âge minimum",
    MAX(age) as "Âge maximum"
FROM etudiants;

SELECT
    age,
    COUNT(*) as "Nombre d'étudiants"
FROM etudiants
GROUP BY age
ORDER BY age;

CREATE VIEW vue_etudiants_actifs AS

SELECT
    id_etudiants,
    nom,
    prenom,
    age,
    email,
    date_inscription
FROM etudiants
WHERE actif = TRUE
;

SELECT * FROM vue_etudiants_actifs ORDER BY nom, prenom;

UPDATE etudiants
SET age = 24, email = 'jean.dupont.nouveau@email.com'
WHERE nom = 'Dupont' AND prenom = 'Jean';


SELECT * FROM etudiants WHERE nom = 'Dupont';
